---
title: "Large Language Models unlock the ecology of species interactions"
subtitle: "Using LLMs to collect species interaction data from an underutilized source: citizen science comments"
author: 
  - __Heng-Xing Zou__
  - Xiaohao Yang
  - Thabassum Hashmi Hajamaideen
  - Olivia Stein
  - Roxanne Beltran
  - Benjamin Freeman
  - Mark Lindquist
  - Eliot Miller
  - Summer Mengarelli
  - Charlotte Probst
  - Fernanda Valdovinos
  - Derek Van Berkel
  - Phoebe Zarnetske
  - Brian Weeks
  - Kai Zhu
description: "In revision, PNAS"
categories:
  - Big data analysis
  - First-author
keywords:
  - citizen science
  - novel ecological data
  - large language model
about:
  template: solana
  links:
    - text: Preprint
      icon: file
      url: "https://www.biorxiv.org/content/10.64898/2026.02.06.704115v1"
format: html
  toc: true
---

In order to accurately evaluate potential shifts in species interactions under climate change, we need more timely observations in nature. Citizen science platforms provide a unique opportunity for crowd-sourced, fast-updating documentation of species interactions. Using advanced Large Language Models (LLMs), I am leading a collaborative effort on collecting species interactions from observation comments on citizen science platforms such as [eBird](ebird.org) and [iNaturalist](inaturalist.org). The resulting datasets have broad spatial and temporal coverage and high spatiotemporal resolution, providing new opportunities for understanding species interactions under global change.

This is a collaborative effort with [Xiaohao Yang](https://www.xiaohaoyportfolio.com/) (PhD Candidate, University of Michigan), Thabassum Hashmi Hajamaideen (undergraduate student, University of Michigan), [Phoebe Zarneske](https://www.communityecologylab.com/) (Michigan State University), [Brian Weeks](https://bcweeks.weebly.com/), [Kai Zhu](https://zhulab.seas.umich.edu/), and an interdisciplinary team from multiple institutions.

The data extraction is supported by a team of excellent undergrads, recuited through University of Michigan’s [Undergraduate Research Opportunity Program](https://lsa.umich.edu/urop): Yuyao (Michelle) Fan, Thabassum (Tab) Hashmi Hajamaideen, Samantha Lukes, Jesse Perrault, Olivia Stein, and Sophia Thomas.
